"""empty message

Revision ID: 60bf91b706de
Revises: 1de6913adf31
Create Date: 2024-03-10 13:01:18.477859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60bf91b706de'
down_revision = '1de6913adf31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generated_value', sa.Float(), nullable=False),
    sa.Column('generation_time', sa.DateTime(), nullable=False),
    sa.Column('data_type_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['data_type_id'], ['data_type.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data')
    # ### end Alembic commands ###
