"""
A new table named "admins" was created with an "id" column as the primary key.
A foreign key constraint is added to the "id" column of the "admins" table,
referencing the "id" column of the "users" table.
A foreign key constraint named "fk_device_user" is created on the "devices" table,
linking its "id" column to the "id" column of the "users" table.
The "password" and "username" columns are dropped from the "devices" table.
A new column named "role" is added to the "users" table.

Revision ID: fbbd12061c83
Revises: 1de6913adf31
Create Date: 2024-03-23 10:46:26.383457

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fbbd12061c83"
down_revision = "1de6913adf31"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admins",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("devices", schema=None) as batch_op:
        batch_op.create_foreign_key("fk_device_user", "users", ["id"], ["id"])
        batch_op.drop_column("password")
        batch_op.drop_column("username")

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("role", sa.String(length=64), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("role")

    with op.batch_alter_table("devices", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "username", sa.VARCHAR(length=80), autoincrement=False, nullable=False
            )
        )
        batch_op.add_column(
            sa.Column(
                "password", sa.VARCHAR(length=256), autoincrement=False, nullable=False
            )
        )
        batch_op.drop_constraint("fk_device_user", type_="foreignkey")

    op.drop_table("admins")
    # ### end Alembic commands ###
