name: Newman Integration Tests

on:
  pull_request:
    branches:
      - master
      - dev
  push:
    branches:
      - master
      - dev
  workflow_dispatch:

jobs:
  newman:
    name: Newman Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          export DATABASE_URL="sqlite:///data.db"
          export JWT_KEY="15835791052248868013867479752485955126834265180411671240111600063995691199944"
          flask db upgrade
          flask run
          rm -f ./instance/data.db
#      - name: Test with pytest
#        run: |
#          pip install pytest pytest-cov
#          pytest tests.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
#          # cd ${GITHUB_WORKSPACE}
#          chmod +x ./test_run.sh
#          sudo ./test_run.sh
      - uses: matt-ball/newman-action@master
        with:
          collection: ./test/postman/REST API IoT.postman_collection.json
          environment: ./test/postman/IoTRestApi.postman_environment.json
